# Generated by Django 4.0.1 on 2022-01-29 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin_settings',
            new_name='Settings',
        ),
    ]
