# Generated by Django 4.0.1 on 2022-01-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_rename_admin_settings_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('project', models.CharField(default=None, max_length=255)),
                ('date', models.CharField(default=None, max_length=255)),
                ('time', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
