# Generated by Django 4.0.1 on 2022-01-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.CharField(blank=True, choices=[('Http', 'Http'), ('request', 'Request')], max_length=10),
        ),
    ]
