# Generated by Django 4.0.2 on 2022-02-25 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Square', '0003_project_description'),
        ('Admin', '0005_rename_task_task_task_type_task_in_execute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Square.project'),
        ),
    ]
