# Generated by Django 4.0.1 on 2022-02-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tasktype_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
