# Generated by Django 4.0.1 on 2022-02-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tasktype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='type',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
