# Generated by Django 4.0.1 on 2022-02-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tasktype_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktype',
            name='name',
        ),
    ]
