# Generated by Django 4.0.1 on 2022-02-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_alter_task_task_type_alter_tasktype_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time',
        ),
    ]
