# Generated by Django 4.0.1 on 2022-02-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_remove_task_date_remove_task_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.AlterField(
            model_name='task',
            name='enable',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
