# Generated by Django 4.0.1 on 2022-03-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_remove_task_project_alter_task_enable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CI', models.CharField(blank=True, default='CI0000000', max_length=255, null=True)),
                ('SubSystem', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Fp_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestSettingsCancelExternalApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CI', models.CharField(blank=True, default='CI0000000', max_length=255, null=True)),
                ('SubSystem', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name_of_system', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name_of_services', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('delay_URL', models.CharField(blank=True, default='http://localhost:8080/', max_length=255, null=True)),
                ('default_ms', models.CharField(blank=True, default=1000, max_length=255, null=True)),
                ('critical_ms', models.CharField(blank=True, default=2800, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestSettingsDelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_system', models.CharField(blank=True, default='CI0000000', max_length=255, null=True)),
                ('name_of_services', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('delay_URL', models.CharField(blank=True, default='http://localhost:8080/', max_length=255, null=True)),
                ('default_ms', models.CharField(blank=True, default=1000, max_length=255, null=True)),
                ('critical_ms', models.CharField(blank=True, default=2800, max_length=255, null=True)),
            ],
        ),
    ]
