# Generated by Django 4.0.1 on 2022-03-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_projectlist_testsettingscancelexternalapi_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestSettingsCancelExternalApi',
            new_name='SettingsCancelExternalApi',
        ),
        migrations.RenameModel(
            old_name='TestSettingsDelay',
            new_name='SettingsDelay',
        ),
    ]
