# Generated by Django 4.0.1 on 2022-03-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_rename_testsettingscancelexternalapi_settingscancelexternalapi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingscancelexternalapi',
            name='CI',
        ),
        migrations.RemoveField(
            model_name='settingscancelexternalapi',
            name='SubSystem',
        ),
        migrations.AlterField(
            model_name='projectlist',
            name='Fp_name',
            field=models.CharField(blank=True, default='DEBET_CARD', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectlist',
            name='SubSystem',
            field=models.CharField(blank=True, default='mySubsystem', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='settingscancelexternalapi',
            name='critical_ms',
            field=models.CharField(blank=True, default=60, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='settingscancelexternalapi',
            name='default_ms',
            field=models.CharField(blank=True, default=1, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='settingsdelay',
            name='critical_ms',
            field=models.CharField(blank=True, default=2.8, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='settingsdelay',
            name='default_ms',
            field=models.CharField(blank=True, default=1, max_length=255, null=True),
        ),
    ]
