# Generated by Django 4.0.1 on 2022-03-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_remove_settingscancelexternalapi_ci_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectList',
        ),
    ]
