# Generated by Django 4.0.1 on 2022-02-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Square', '0002_category_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
