# Generated by Django 4.0.1 on 2022-03-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Square', '0003_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
